# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
categories = Category.create([{ name: "Theatre"}, { name: "Art" }, {name: "Music"}, {name: "Architecture & Design"}, {name: "Film"}])
moods = Mood.create([{ name: 'Happy' }, { name: 'Moody' }, { name: 'Feel Something' }, { name: 'Comedy' }, { name: 'Dancey' }, { name: 'Culturey' }])

Art.create(name: "Museum of the Moving Image", family: true, musical: false, price: 1, category_id: 5, mood_id: 1, url: "http://movingimage.us/")
Art.create(name: "Smithsonian Cooper-Hewitt National Design Museum", family: false, musical: false, price: 0, category_id: 4, mood_id: 6, url: "https://www.cooperhewitt.org/")
Art.create(name: "Dizzy's Club Coca-Cola", family: false, musical: false, price: 4, category_id: 3, mood_id: 6, url: "https://2021.jazz.org/dizzys-club")
Art.create(name: "Frick Collection", family: false, musical: false, price: 3, category_id: 2, mood_id: 6, url: "http://www.frick.org/")
Art.create(name: "Aladdin", family: true, musical: true, price: 5, category_id: 1, mood_id: 1, url: "https://aladdinthemusical.com/tickets/")
Art.create(name: "Come From Away", family: false, musical: true, price: 4, category_id: 4, mood_id: 6, url: "https://comefromaway.com/index.php")
Art.create(name: "David Byrne's Utopia", family: false, musical: true, price: 5, category_id: 3, mood_id: 6, url: "https://americanutopiabroadway.com/")
Art.create(name: "Hadestown", family: true, musical: true, price: 5, category_id: 2, mood_id: 6, url: "https://www.hadestown.com/")
Art.create(name: "Hamilton", family: true, musical: true, price: 5, category_id: 1, mood_id: 1, url: "https://hamiltonmusical.com/new-york/home/")
Art.create(name: "New Museum", family: false, musical: false, price: 2, category_id: 2, mood_id: 6, url: "https://www.newmuseum.org/visit")
Art.create(name: "Metropolitan Museum of Art", family: false, musical: false, price: 3, category_id: 2, mood_id: 6, url: "https://www.metmuseum.org/")
Art.create(name: "Robin Museum of Art", family: false, musical: false, price: 2, category_id: 2, mood_id: 6, url: "https://rubinmuseum.org/")
Art.create(name: "Museum of American Indian", family: true, musical: false, price: 0, category_id: 2, mood_id: 6, url: "https://americanindian.si.edu/")
Art.create(name: "Guggenheim", family: false, musical: false, price: 3, category_id: 2, mood_id: 6, url: "https://www.guggenheim.org/")
Art.create(name: "New York Transit Museum", family: true, musical: false, price: 1, category_id: 4, mood_id: 1, url: "https://www.nytransitmuseum.org/")
Art.create(name: "Socrates Sculpture Park", family: true, musical: false, price: 0, category_id: 4, mood_id: 1, url: "https://socratessculpturepark.org/")
Art.create(name: "Christie's Sculpture Garden", family: true, musical: false, price: 0, category_id: 4, mood_id: 6, url: "https://www.christies.com/locations/salerooms/new-york/")
Art.create(name: "Museum of Art and Design", family: false, musical: false, price: 2, category_id: 4, mood_id: 6, url: "https://madmuseum.org/about")
Art.create(name: "Let Love Inn", family: false, musical: false, price: 1, category_id: 3, mood_id: 5, url: "http://letloveinn.com/")
Art.create(name: "Arlene's Grocery", family: false, musical: false, price: 1, category_id: 3, mood_id: 5, url: "https://www.arlenesgrocerynyc.com/")
Art.create(name: "Rockwood Music Hall", family: false, musical: false, price: 1, category_id: 3, mood_id: 1, url: "https://rockwoodmusichall.com/")
Art.create(name: "Carnegie Hall", family: false, musical: false, price: 3, category_id: 3, mood_id: 6, url: "https://www.carnegiehall.org/")
Art.create(name: "Lincoln Center", family: false, musical: false, price: 3, category_id: 3, mood_id: 3, url: "http://www.lincolncenter.org/music")
Art.create(name: "Whitney Museum", family: false, musical: false, price: 2, category_id: 2, mood_id: 6, url: "https://whitney.org/visit")
Art.create(name: "The Museum of Modern Art", family: false, musical: false, price: 2, category_id: 2, mood_id: 3, url: "https://www.moma.org/")
Art.create(name: "The Cloisters", family: true, musical: false, price: 2, category_id: 2, mood_id: 3, url: "https://www.metmuseum.org/visit/plan-your-visit/met-cloisters")
Art.create(name: "The Lehmen Triology", family: false, musical: false, price: 5, category_id: 1, mood_id: 6, url: "https://thelehmantrilogy.com/")
Art.create(name: "The Lion King", family: true, musical: true, price: 5, category_id: 1, mood_id: 3, url: "https://lionking.com/")
Art.create(name: "Six: The Musical", family: false, musical: true, price: 5, category_id: 1, mood_id: 3, url: "https://sixonbroadway.com/")
Art.create(name: "To Kill A Mockingbird", family: false, musical: false, price: 5, category_id: 1, mood_id: 6, url: "https://tokillamockingbirdbroadway.com/")
Art.create(name: "Wicked", family: true, musical: true, price: 5, category_id: 1, mood_id: 3, url: "https://wickedthemusical.com/")
Art.create(name: "Blue Man Group", family: true, musical: false, price: 4, category_id: 1, mood_id: 1, url: "https://www.blueman.com/new-york/buy-tickets")
Art.create(name: "Chasing Jack", family: false, musical: false, price: 4, category_id: 1, mood_id: 3, url: "https://www.chasingjacktheplay.com/")
Art.create(name: "Drunk Shakespeare", family: false, musical: false, price: 3, category_id: 1, mood_id: 4, url: "https://www.drunkshakespeare.com/welcome")
Art.create(name: "Jersey Boys", family: true, musical: true, price: 5, category_id: 1, mood_id: 1, url: "https://jerseyboysinfo.com/newyork")
Art.create(name: "The Office: A Musical Parody", family: false, musical: true, price: 3, category_id: 1, mood_id: 4, url: "https://theofficemusicalparody.com/")
Art.create(name: "The Play That Goes Wrong", family: false, musical: false, price: 3, category_id: 1, mood_id: 4, url: "https://broadwaygoeswrong.com/")
Art.create(name: "Stomp", family: true, musical: false, price: 3, category_id: 1, mood_id: 1, url: "https://stomponline.com/")
Art.create(name: "Nitehawk Cinema", family: false, musical: false, price: 1, category_id: 5, mood_id: 3, url: "https://nitehawkcinema.com/")

Art.create(name: "Shakespeare in the Park", family: true, musical: false, price: 0, category_id: 1, mood_id: 1, url: "https://publictheater.org/visit/directions/")
Art.create(name: "Shakepeare in the Park", family: true, musical: false, price: 0, category_id: 1, mood_id: 2, url: "https://publictheater.org/visit/directions/")
Art.create(name: "Shakepeare in the Park", family: true, musical: false, price: 0, category_id: 1, mood_id: 3, url: "https://publictheater.org/visit/directions/")
Art.create(name: "Shakepeare in the Park", family: true, musical: false, price: 0, category_id: 1, mood_id: 3, url: "https://publictheater.org/visit/directions/")
Art.create(name: "Shakepeare in the Park", family: true, musical: false, price: 0, category_id: 1, mood_id: 3, url: "https://publictheater.org/visit/directions/")
Art.create(name: "Shakepeare in the Park", family: true, musical: false, price: 0, category_id: 1, mood_id: 6, url: "https://publictheater.org/visit/directions/")

Art.create(name: "MoMA PS1", family: true, musical: false, price: 0, category_id: 2, mood_id: 1, url: "https://www.moma.org/about/")
Art.create(name: "MoMA PS1", family: true, musical: false, price: 0, category_id: 2, mood_id: 2, url: "https://www.moma.org/about/")
Art.create(name: "MoMA PS1", family: true, musical: false, price: 0, category_id: 2, mood_id: 3, url: "https://www.moma.org/about/")
Art.create(name: "MoMA PS1", family: true, musical: false, price: 0, category_id: 2, mood_id: 4, url: "https://www.moma.org/about/")
Art.create(name: "MoMA PS1", family: true, musical: false, price: 0, category_id: 2, mood_id: 5, url: "https://www.moma.org/about/")
Art.create(name: "MoMA PS1", family: true, musical: false, price: 0, category_id: 2, mood_id: 6, url: "https://www.moma.org/about/")

Art.create(name: "Find buskers in Central Park", family: true, musical: false, price: 0, category_id: 3, mood_id: 1, url: "https://en.wikipedia.org/wiki/Central_Park")
Art.create(name: "Find buskers in Central Park", family: true, musical: false, price: 0, category_id: 3, mood_id: 2, url: "https://en.wikipedia.org/wiki/Central_Park")
Art.create(name: "Find buskers in Central Park", family: true, musical: false, price: 0, category_id: 3, mood_id: 3, url: "https://en.wikipedia.org/wiki/Central_Park")
Art.create(name: "Find buskers in Central Park", family: true, musical: false, price: 0, category_id: 3, mood_id: 4, url: "https://en.wikipedia.org/wiki/Central_Park")
Art.create(name: "Find buskers in Central Park", family: true, musical: false, price: 0, category_id: 3, mood_id: 5, url: "https://en.wikipedia.org/wiki/Central_Park")
Art.create(name: "Find buskers in Central Park", family: true, musical: false, price: 0, category_id: 3, mood_id: 6, url: "https://en.wikipedia.org/wiki/Central_Park")

Art.create(name: "Central Park", family: true, musical: false, price: 0, category_id: 4, mood_id: 1, url: "https://en.wikipedia.org/wiki/Central_Park")
Art.create(name: "Central Park", family: true, musical: false, price: 0, category_id: 4, mood_id: 2, url: "https://en.wikipedia.org/wiki/Central_Park")
Art.create(name: "Central Park", family: true, musical: false, price: 0, category_id: 4, mood_id: 3, url: "https://en.wikipedia.org/wiki/Central_Park")
Art.create(name: "Central Park", family: true, musical: false, price: 0, category_id: 4, mood_id: 4, url: "https://en.wikipedia.org/wiki/Central_Park")
Art.create(name: "Central Park", family: true, musical: false, price: 0, category_id: 4, mood_id: 5, url: "https://en.wikipedia.org/wiki/Central_Park")
Art.create(name: "Central Park", family: true, musical: false, price: 0, category_id: 4, mood_id: 6, url: "https://en.wikipedia.org/wiki/Central_Park")

Art.create(name: "Movies in Bryant Park", family: true, musical: false, price: 0, category_id: 5, mood_id: 1, url: "https://bryantpark.org/programs/movie-nights")
Art.create(name: "Movies in Bryant Park", family: true, musical: false, price: 0, category_id: 5, mood_id: 3, url: "https://bryantpark.org/programs/movie-nights")
Art.create(name: "Movies in Bryant Park", family: true, musical: false, price: 0, category_id: 5, mood_id: 2, url: "https://bryantpark.org/programs/movie-nights")
Art.create(name: "Movies in Bryant Park", family: true, musical: false, price: 0, category_id: 5, mood_id: 4, url: "https://bryantpark.org/programs/movie-nights")
Art.create(name: "Movies in Bryant Park", family: true, musical: false, price: 0, category_id: 5, mood_id: 5, url: "https://bryantpark.org/programs/movie-nights")
Art.create(name: "Movies in Bryant Park", family: true, musical: false, price: 0, category_id: 5, mood_id: 6, url: "https://bryantpark.org/programs/movie-nights")

